### ISSUE TITLE
This is a pretty cool find!

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/github-backend-lacks-url-validation#1]
Have you raised this with GitHub at all? 😆 I don't really know where you'd submit it or if they even care about this (they probably don't) but it's worth trying maybe? Maybe not. 🤷‍♂️

**Comment by spenserblack** [comment]
No, I haven't raised it with GitHub. I suppose the place to submit it would be the [community discussions](https://github.com/community/community/discussions).

I'd be scared to get it fixed, though, since some services may take advantage of this. For example, Vercel does not include the protocol in the URL (`foo.vercel.app` instead of `https://foo.vercel.app`) when setting the repo's website, which is actually an *invalid `<input type="url">` value.* So the question is: should the input become less strict (just make it `type="text"`), or should the backend become more strict and potentially break some things :thinking:

It seems like GitHub has anticipated invalid URLs though, since they must be doing some sort of error-catching when "linkifying" this value :shrug:
